version: '2.2'
metadata:
  type-aliases:
    uint16:
      class: int
      size: 16

  clocks:
    default: 
      freq: 1000000000
      offset:
        seconds: 1434072888
      $return-ctype: uint64_t

  trace:
    byte-order: le
  
  
  streams:
    default: 
      packet-context-type:
        class: struct
        fields:
          packet_size: uint16
          content_size: uint16
      events:
        my_event:
          payload-type:
            class: struct
            fields:
              my_field:
                class: int
                size: 8

      